### ISSUE TITLE
Decide if this has future utility?

### ISSUE THREAD

**Issue by steviewanders** [HakaiInstitute/hakai-ckan-records-checks#5]

**Comment by timvdstap** [comment]
Ideally for any future record submissions all items included within the ckan-record-checker are investigated in the review process. That being said, for the time being I do think this checker has utility to ensure that all currently published records meet our established criteria. I might need a brief refresher on how to best interact with it though, and actually carve out time to address identified metadata record issues.

**Comment by fostermh** [comment]
it all runs within github and you review by going to https://hakaiinstitute.github.io/hakai-ckan-records-checks/. I have never used it, but perhaps should. :-)

**Comment by fostermh** [comment]
looking at the 'errors' it appears they are mostly (perhaps all?) info and warning level. It also appears many of them could be resolved with a bulk update to add a ROR for the hakai institute. The repo might have utility as an interesting graphic and double check we didn't miss things in our review but I doubt any features would be added to it unless we find many deficiencies in our existing records.

**Comment by fostermh** [comment]
As a test, I did a bulk update to all the occurrences of the hakai organization in our firebase backend to add a ROR if it did not already have one set. this fixed 200 warnings. Other similar issues may be solvable on mass. fingers crossed. 

For now, it appears to still be a usefull tool.

**Comment by steviewanders** [comment]
Nice, then it serves a purpose as an occaisonal linter and can live to see another moon.
